### PR TITLE
Mission states management

### LINKED ISSUE #5: Set up travis build

### LINKED ISSUE #11: The supervisor must be able to manage execution of many missions at the same time
The supervisor should be able to manage a set of mission execution sessions. Each mission is spawned in a new JVM, so the mission executions are a set of java processes which are running in parallel on the host where the supervisor is running.

### LINKED ISSUE #16: Implement the former client interface
The previous client interface allows to run a mission to completion or step over a mission (java debugging). When the operator chooses to run a mission; he has the possibility to:
- get the mission result.
- cancel the mission.

On the other hand, stepping over a mission allows the operator to:
- cancel the mission.
- run the mission to completion.
- execute a step debugging and get the step result (the mission result if it is the last step).

If implemented, this interface would be a layer upon the existing generic interface. Therefore, it would be a particular case of the API.

Is that interface relevant, should it be implemented?

### LINKED ISSUE #17: Send possible commands to client
The operator receives the acceptance status of a sent command: whether it was accepted by the supervisor or not. But it would be more interesting if the client has the possibility to know the the available commands before choosing one of them. So the supervisor must send the list of possible commands whenever the mission execution state changes. This can be accomplished using:
- The events flux received by the client.
- Another flux dedicated only for this requirement.
- The heartbeat mechanism which notifies MolR server.

### LINKED ISSUE #19: Use logging log4j2 instead of printStackTrace

### LINKED ISSUE #20: Improve the project architecture

### LINKED ISSUE #21: Remove the stateless supervisor
Stateless supervisors are not needed. We need always to get the supervisor state. So the interface and implementation of stateless supervisors should be removed.

### LINKED ISSUE #22: Use the plain reactive streams API with publisher instead of concrete implementation on the interface level

### LINKED ISSUE #23: Get the mission states
The client must be able to get a states flux using the client controller. The current mission state allows the operator to know the current status and the possible commands for example.

### PR DESCRIPTION
**Pull request by yassine-kr**
fixes #16 
fixes #17 
fixes #19 
fixes #20 
fixes #21 
fixes #22 
fixes #23
fixes #5 
fixes #11

### CODE REVIEW

File: api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+/**
+ * A request sent to MolR server and a supervisor to execute a command
+ * @author yassine-kr
+ */
+public class MissionCommandRequest {
+    private String missionId;
+    private MoleExecutionCommand command;
+
+    public MissionCommandRequest() {
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java]: remove empty constructor

File: api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+    public MissionCommandRequest(String missionId, MoleExecutionCommand command) {
+        this.missionId = missionId;
+        this.command = command;
+    }
+
+    public String getMissionId() {
+        return missionId;
+    }
+
+    public void setMissionId(String missionId) {
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java]: Do you have a good reason for exposing setters?

Make this class immutable, e.g. no setters, and final class.

File: api/src/main/java/cern/molr/mole/supervisor/MoleCommandListener.java [hunk 3]
```diff
@@ -3,7 +3,7 @@
 /**
  * Listener for commands sent by supervisor to JVM
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MoleCommandListener.java]: JVM -> MoleRunner

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandResponse.java [hunk 4]
```diff
@@ -0,0 +1,9 @@
+package cern.molr.mole.supervisor;
+
+/**
+ * Generic result of a command request (not the result of the command execution), this data should be sent by JVM as
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandResponse.java]: this isn't what is written in the sequence diagram on the white board.
On the white board, the command execution returns a Mono, that will provide the command response.
So it shouldn't be in the event flux.

What's the difference between the command request response and the command execution result?

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java [hunk 5]
```diff
@@ -1,26 +1,41 @@
 package cern.molr.mole.supervisor;
 
 /**
- * Event sent by JVM which tells to supervisor the status of the last command received
- * @author yassine
+ * Event sent by JVM which tells to supervisor the status of the last received command
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java]: JVM -> MoleRunner
I'll stop commenting on this, but please address all the JVM to MoleRunner renaming

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java [hunk 6]
```diff
@@ -1,26 +1,41 @@
...
+ * @author yassine-kr
  */
 public abstract class MoleExecutionCommandStatus implements MoleExecutionEvent{
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java]: ident this file, and others, the entire project basically, the spacing is not consistent

File: api/src/main/java/cern/molr/mole/Mole.java [hunk 7]
```diff
@@ -4,23 +4,27 @@
...
-import java.lang.reflect.Method;
-import java.util.List;
 
 import cern.molr.exception.IncompatibleMissionException;
 import cern.molr.exception.MissionExecutionException;
 import cern.molr.mission.Mission;
 
 /**
- * A {@link Mole} executes a given mission. Only a {@link Mole} knows how to run a mission.
+ * A {@link Mole} executes a given mission. Only a {@link Mole} knows how to control a mission.
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/Mole.java]: yes just the refactoring went sideways

File: api/src/main/java/cern/molr/mole/supervisor/JVMState.java [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+     * Method which verify whether a command is accepted by the current state
+     * @param command
+     * @throws Exception if the command is not accepted
+     */
+    void acceptCommand(MoleExecutionCommand command) throws CommandNotAcceptedException;
+
+    /**
+     * Change the current state according to the last accepted command
+     */
+    void changeState();
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/JVMState.java]: The logic of changing the current state is encapsulated in an instance of MoleRunnerState (JVMState). This class will be modified when integrating the mole state.

File: api/src/main/java/cern/molr/mole/supervisor/address/AddressGetter.java [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+        public void setPort(int port) {
+            this.port = port;
+        }
+    }
+
+    /**
+     *
+     * @param listener listener to be notified when the getter gets the address
+     */
+    void addListener(AddressGetterListener listener);
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/mole/supervisor/address/AddressGetter.java]: I'll need you to show me where this is used. I find the listener implementation quite heavy

File: api/src/main/java/cern/molr/mole/supervisor/JVMState.java [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+ * Represents a JVM state.
+ * @author yassine-kr
+ */
+public interface JVMState {
+    /**
+     * Method which verify whether a command is accepted by the current state
+     * @param command
+     * @throws Exception if the command is not accepted
+     */
+    void acceptCommand(MoleExecutionCommand command) throws CommandNotAcceptedException;
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/JVMState.java]: Does only accept or reject a command.

File: api/src/main/java/cern/molr/mole/supervisor/JVMState.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/JVMState.java]: The state change will be triggered by an event not a a command.

File: api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java (hunk 1 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java]: needed for deserialization

File: api/src/main/java/cern/molr/mission/controller/custom/CustomRunMissionController.java [hunk 11]
```diff
@@ -2,20 +2,23 @@
...
+ * A custom controller used for a simple control of a running {@link Mission}
+ * implementation should be a layer upon {@link ClientMissionController}
  * 
- * @author nachivpn 
+ * @author nachivpn
+ * @author yassine-kr
  * @param <T>
  */
-public interface RunMissionController<T> {
+public interface CustomRunMissionController<T> {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mission/controller/custom/CustomRunMissionController.java]: done, the whole project architecture was improved.

File: api/src/main/java/cern/molr/mission/service/MissionExecutionService.java [hunk 12]
```diff
@@ -4,22 +4,23 @@
...
+ * A service used by client to control a remote mission execution on a supervisor
+ * @author yassine-kr
  */
 public interface MissionExecutionService {
 
-    <I,O> CompletableFuture<RunMissionController<O>> runToCompletion(String missionDefnClassName, I args, Class<I> cI, Class<O> cO) throws UnsupportedOutputTypeException;
-    
-    <I,O> CompletableFuture<StepMissionController<O>> step(String missionDefnClassName, I args);
+    /**
+     * A method which send a mission instantiation request to the MolR server
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mission/service/MissionExecutionService.java]: done

File: api/src/main/java/cern/molr/mole/Mole.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/Mole.java]: done

File: api/src/main/java/cern/molr/mole/supervisor/JVMState.java [hunk 13]
```diff
@@ -0,0 +1,23 @@
+package cern.molr.mole.supervisor;
+
+import cern.molr.exception.CommandNotAcceptedException;
+
+/**
+ * Represents a JVM state.
+ * @author yassine-kr
+ */
+public interface JVMState {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/JVMState.java]: done

File: api/src/main/java/cern/molr/mole/supervisor/MoleCommandListener.java (hunk 3 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MoleCommandListener.java]: done

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandResponse.java (hunk 4 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandResponse.java]: The client gets a Mono when sending a command request to MolR server. MolR server gets a Mono when forwarding the command request, the supervisor handler gets a Mono when forwarding the command request to the supervisor service. This service calls the session controller which sends the command to the Mole runner and waits for a command status using its events reader. So the status is sent back to the controller as an event data, then it will be transformed to a CommandResponse.

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java (hunk 5 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java]: done

File: api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java [hunk 14]
```diff
@@ -1,12 +1,52 @@
 package cern.molr.server;
 
 import cern.molr.mole.supervisor.MoleSupervisor;
+import com.fasterxml.jackson.annotation.JsonIgnore;
+
+import java.util.Optional;
 
 /**
- * It represents a supervisor which can tell whether it is idle or not
+ * It represents a supervisor which can gives its state
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java]: class deleted

File: api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java [hunk 15]
```diff
@@ -1,12 +1,52 @@
...
+    Optional<State> getState();
+
+    /**
+     * Supervisor state
+     */
+    class State{
+        private int numMissions;
+        private int maxMissions;
+
+        public State() {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java]: needed for deserialization

File: api/src/main/java/cern/molr/type/ManuallySerializable.java [hunk 16]
```diff
@@ -0,0 +1,34 @@
...
+/**
+ * Classes which has to be manually serializable. If the automatic serialization using Jackson library fails, the
+ * manual serialization is used
+ * @author yassine-kr
+ */
+public interface ManuallySerializable {
+
+    /**
+     * Method which returns the map representing the json object.
+     * @return
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/type/ManuallySerializable.java]: you should write something in the "@return "

Comment (jcgarnier) [reply api/src/main/java/cern/molr/type/ManuallySerializable.java]: it's not the only place I saw this, please correct everywhere

File: api/src/main/java/cern/molr/type/either/Either.java [hunk 17]
```diff
@@ -4,19 +4,23 @@
 
 package cern.molr.type.either;
 
+import java.util.function.Consumer;
 import java.util.function.Function;
 
 /**
  * A simple data type for constructing a disjoint union (or sum type) of two types. 
  * Offers pattern matching on Either values & some powerful combinators to combine Either values
```
Comment (jcgarnier) [inline api/src/main/java/cern/molr/type/either/Either.java]: & -> and

**Comment by jcgarnier** [comment]
The merge request went from 189 files to 254, and all my comments were lost. We should have synchronized so that we could finish the review before you push any changes...

**Comment by yassine-kr** [comment]
I am still able to display your comments that you did on Friday and the ones you wrote today. Do you mean that you lost other comments because there were pushes between the beginning of the review and its end? In this case, I am sorry for your loss and I suggest fixing a time of the day when I can push changes or simply ask you if I can push my changes.

File: api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java (hunk 6 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MoleExecutionCommandStatus.java]: code formatted

File: api/src/main/java/cern/molr/mole/supervisor/address/AddressGetter.java (hunk 9 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/address/AddressGetter.java]: The AddressGetter is an object that is able to return the address of the supervisor. This address has to be reachable from MolR server, the supervisor sends it in the registration request. The simple implementation is a spring component which waits for the initialization event of the server to notify its listeners after retrieving the host name and the port on which the server is running. There is one listener which sends the registration request to MolR server when notified.

File: client-api/src/main/java/cern/molr/client/api/ClientMissionController.java [hunk 18]
```diff
@@ -0,0 +1,36 @@
...
+    /**
+     * A method which gets an events flux generated by the supervisor where the mission is being executed
+     *
+     * @return
+     */
+    Flux<MissionEvent> getFlux();
+
+
+    /**
+     * A method which send a command to the supervisor where the mission is being executed
```
Comment (jcgarnier) [inline client-api/src/main/java/cern/molr/client/api/ClientMissionController.java]: command -> javadoc ref to MissionCommand

File: client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java [hunk 19]
```diff
@@ -0,0 +1,28 @@
...
+ * Copyright (c) 2017 European Organisation for Nuclear Research (CERN), All Rights Reserved.
+ */
+
+package cern.molr.client.api;
+
+import reactor.core.publisher.Mono;
+
+
+/**
+ * A service used by client to control a remote mission execution on a supervisor
```
Comment (jcgarnier) [inline client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java]: "used by clients" or "used by the client"

File: client/build.gradle [hunk 20]
```diff
@@ -1,5 +1,15 @@
+configurations.all {
+    /*This dependency is automatically required by slf4j, it should be excluded to avoid infinite loop between slf4j
```
Comment (jcgarnier) [inline client/build.gradle]: is this true? I never had this problem. 
SLF4J as such doesn't even exist. Is it required by SLF4J-API? SLF4J-SDK?

File: client/src/main/java/cern/molr/client/SampleOperator.java [hunk 21]
```diff
@@ -0,0 +1,112 @@
...
+ * Operator example
+ *
+ * @author yassine
+ */
+public class SampleOperator {
+
+    private MissionExecutionService service;
+
+    public SampleOperator(MissionExecutionService service) {
+        this.service = service;
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/SampleOperator.java]: it should be checked against null

File: client/src/main/java/cern/molr/client/SampleOperator.java [hunk 22]
```diff
@@ -0,0 +1,112 @@
+package cern.molr.client;
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/SampleOperator.java]: this package contains demo code and production code, split them in different packages accordingly

File: client/src/main/java/cern/molr/client/SampleOperator.java [hunk 23]
```diff
@@ -0,0 +1,112 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import java.util.concurrent.CountDownLatch;
+
+/**
+ * Operator example
+ *
+ * @author yassine
+ */
+public class SampleOperator {
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/SampleOperator.java]: why Sample? 
ExampleOpertor, or OperatorDemo

File: client/src/main/java/cern/molr/client/SampleOperator.java [hunk 24]
```diff
@@ -0,0 +1,112 @@
...
+        CountDownLatch startSignal = new CountDownLatch(1);
+        CountDownLatch endSignal = new CountDownLatch(5);
+
+        Mono<ClientMissionController> futureController = service.instantiate(missionClass.getCanonicalName(), 100);
+        futureController.doOnError(Throwable::printStackTrace).subscribe((controller) -> {
+            controller.getFlux().subscribe((event) -> {
+                System.out.println(execName + " event: " + event);
+                events.add(event);
+                endSignal.countDown();
+                if (event instanceof SessionInstantiated)
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/SampleOperator.java]: respect our coding conventions, described here: https://wikis.cern.ch/display/MPESC/Java
They mainly follow the recommendations: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-142311.html#431

so no if without curly brackets

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 25]
```diff
@@ -0,0 +1,117 @@
...
+
+            String host = properties.getProperty("host");
+            int port = Integer.parseInt(properties.getProperty("port"));
+
+            client = new MolrWebClient(host, port);
+            clientSocket = new MolrWebSocketClient(host, port);
+
+        } catch (Exception e) {
+            LOGGER.error("error while trying to get client properties", e);
+            client = new MolrWebClient("localhost", 8000);
```
[the remark this answers is not in the document]
Comment (jcgarnier) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: it basically means that the user asks for something, and something else can be given to him. He would see the thing running, but actually it's not what he wanted

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 26]
```diff
@@ -0,0 +1,117 @@
...
+            clientSocket = new MolrWebSocketClient("localhost", 8000);
+        }
+    }
+
+    public MissionExecutionServiceImpl(String host, int port) {
+        client = new MolrWebClient(host, port);
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: why no exception + error in this case?

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 27]
```diff
@@ -0,0 +1,117 @@
...
+            properties.load(input);
+
+            String host = properties.getProperty("host");
+            int port = Integer.parseInt(properties.getProperty("port"));
+
+            client = new MolrWebClient(host, port);
+            clientSocket = new MolrWebSocketClient(host, port);
+
+        } catch (Exception e) {
+            LOGGER.error("error while trying to get client properties", e);
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: exception message should report more information to help someone understand the problems when they occur: here the host and port must be added

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 28]
```diff
@@ -0,0 +1,117 @@
...
+                        .thenApply(tryResp -> tryResp.match(
+                                (Throwable e) -> {
+                                    throw new CompletionException(e);
+                                }, InstantiationResponseBean::getMissionExecutionId))
+                        .thenApply(missionExecutionId -> new ClientMissionController() {
+                            @Override
+                            public Flux<MissionEvent> getFlux() {
+                                MissionEventsRequest eventsRequest = new MissionEventsRequest(missionExecutionId);
+                                return clientSocket.receiveFlux("/getFlux", MissionEvent.class, eventsRequest)
+                                        .doOnError((e) -> LOGGER.error("error while receiving events flux", e)).map(
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: error message shjould contain the missionExsecutionId, and missionDfnClassName, otherwise impossible to know which flux is broken

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 29]
```diff
@@ -0,0 +1,117 @@
...
+                                                        .match(MissionException::new, Function.identity()));
+                            }
+
+                            @Override
+                            public Mono<CommandResponse> instruct(MissionCommand command) {
+                                MissionCommandRequest commandRequest = new MissionCommandRequest(missionExecutionId,
+                                        command);
+                                return clientSocket.
+                                        receiveMono("/instruct", CommandResponse.class, commandRequest)
+                                        .doOnError((e) -> LOGGER.error("error while receiving a command response", e))
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: error message shjould contain the missionExsecutionId, and missionDfnClassName, and the commandRequest, in a readable way
otherwise impossible to know which flux is broken

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 30]
```diff
@@ -0,0 +1,117 @@
...
+                                        .map((tryElement) ->
+                                                tryElement.match(CommandResponse.CommandResponseFailure::new,
+                                                        Function.identity()));
+                            }
+                        }).get());
+            } catch (InterruptedException | ExecutionException e) {
+                emitter.error(e.getCause());
```
Comment (jcgarnier) [inline client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: better error message with enough diagnostic data

File: commons/src/main/java/cern/molr/commons/commands/Start.java [hunk 31]
```diff
@@ -0,0 +1,10 @@
+package cern.molr.commons.commands;
+
+import cern.molr.commons.request.MissionCommand;
+
+public class Start implements MissionCommand {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/commands/Start.java]: Do we actually need classes extending the MissionCommand?
It will be difficult to scale no? why not a simple String field in MissionCommand? or enums
What do you see different between each command implementation? between start, terminate, and all the custom commands.

File: commons/src/main/java/cern/molr/commons/events/MissionException.java [hunk 32]
```diff
@@ -0,0 +1,57 @@
...
+/**
+ * Event sent back by the supervisor when there is an exception
+ *
+ * @author yassine-kr
+ */
+public class MissionException implements MissionEvent, ManuallySerializable {
+    private Throwable throwable;
+    private String message;
+
+    public MissionException() {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/MissionException.java]: remove empty constructor

**Comment by yassine-kr** [comment]
Changes commented in #8 : 

- used my github login
- used a properties file for the MolR server host and port in the client program
- the unit tests launch the servers using appropriate ports
- created the issue #19 
- the old code is removed
- applied formatting for limiting the line length to 120 chars
- custom packages removed
- the project contains more java doc
- created the issue #22 
- some typos fixed
- start and terminate methods deleted in MoleController class
- MoleSession -> MissionSession
- MoleSupervisor.isIdle() -> MoleSupervisor.getState()
- removed stateless supervisor interface
- split dependencies in their respective modules
- updated some var names
- formatting the code
- field name "gateway" -> "service" in ServerRestController class
- variable name "flux" -> "executionEventFlux" in ServerRestExecutionService class
- used CountDownLatch instead of Thread.sleep

I improved the websocket session handlers code in #24: I created a new class DataExchangeBuilder which builds a publisher that reads the received value then generates a flux. This builder is used by four classes in the project.

Project architecture updated in #24:
There are 9 modules:
- commons: it contains common api, its implementation and classes used by other modules.
- client-api: it contains only the client api.
- client: it contains an implementation of the client api, and classes for executing a sample client code.
- server-api: it contains only the server api.
- server: it contains an implementation of the server api, and classes for launching the server and handling requests.
- supervisor-api: it contains only the supervisor api.
- supervisor: it contains an implementation of the supervisor api, and classes for launching the server and handling requests.
- sample: it contains examples of missions and moles.
- test: it contains unit tests for testing the framework components.

File: commons/src/main/java/cern/molr/commons/events/MissionException.java [hunk 33]
```diff
@@ -0,0 +1,57 @@
...
+    public MissionException(Throwable throwable) {
+        this.throwable = throwable;
+        this.message = throwable.getMessage();
+    }
+
+    public Throwable getThrowable() {
+        return throwable;
+    }
+
+    public void setThrowable(Throwable throwable) {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/MissionException.java]: remove the setters, you don't need them, the exception should be built once and never be modified. It should be immutable. So no setters, and final class (like in effective java I passed to you last time)

Comment (jcgarnier) [reply commons/src/main/java/cern/molr/commons/events/MissionException.java]: or do you need setters for serialization? in this case document it

File: commons/src/main/java/cern/molr/commons/events/MissionFinished.java [hunk 34]
```diff
@@ -0,0 +1,35 @@
+package cern.molr.commons.events;
+
+import cern.molr.commons.response.MissionEvent;
+
+/**
+ * Event sent back by the supervisor when the mission is finished
+ *
+ * @author yassine-kr
+ */
+public class MissionFinished implements MissionEvent {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/MissionFinished.java]: final class

File: commons/src/main/java/cern/molr/commons/events/MissionStarted.java [hunk 35]
```diff
@@ -0,0 +1,36 @@
...
+ * Event sent back by the supervisor when the mission is started
+ *
+ * @author yassine-kr
+ */
+public class MissionStarted implements MissionEvent {
+    private String missionClassName;
+    private Object argument;
+    private String moleClassName;
+
+    public MissionStarted() {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/MissionStarted.java]: remove empty constructor + make class final if possible

File: commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java [hunk 36]
```diff
@@ -0,0 +1,13 @@
...
+
+import cern.molr.commons.response.MissionEvent;
+
+/**
+ * Event sent back by the supervisor when the session is instantiated.
+ * When the JVM is created for example
+ *
+ * @author yassine-kr
+ */
+public class SessionInstantiated implements MissionEvent {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java]: same than for Command, do we need one implementation per MissionEvent? or could it be more scalable

File: commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java [hunk 37]
```diff
@@ -0,0 +1,13 @@
+package cern.molr.commons.events;
+
+import cern.molr.commons.response.MissionEvent;
+
+/**
+ * Event sent back by the supervisor when the session is instantiated.
+ * When the JVM is created for example
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java]: JVM -> MoleRunner?

File: commons/src/main/java/cern/molr/commons/events/SessionTerminated.java [hunk 38]
```diff
@@ -0,0 +1,13 @@
+package cern.molr.commons.events;
+
+import cern.molr.commons.response.MissionEvent;
+
+/**
+ * Event sent back by the supervisor when the session is terminated
+ * When the JVM is destroyed for example
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/events/SessionTerminated.java]: JVM -> MoleRunner ?

File: commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java [hunk 39]
```diff
@@ -0,0 +1,24 @@
+package cern.molr.commons.exception;
+
+
+/**
+ * Thrown when the supervisor reject the execution of a command because of the current Mole runner state
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java]: rejects
Mole runner -> MoleRunner  == MoleRunner is actually a thing, so every time it is referenced it should be done using the same name, not sometimes MoleRunner, sometimes Mole runner, sometmies mole runner, etc. Always the same: MoleRunner

File: commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java [hunk 40]
```diff
@@ -0,0 +1,24 @@
+package cern.molr.commons.exception;
+
+/**
+ * Thrown when the MolR server or a supervisor does not accept to execute a mission; for example because of the mission
+ * type or the fact that the max number of running missions is achieved
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java]: is achieved -> was reached

File: commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java [hunk 41]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * @author yassine-kr
+ */
+public class CommandNotAcceptedException extends Exception {
+
+    private static final long serialVersionUID = 195586081128114794L;
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java]: we usually don't use a random servialVersionUID value, but we start from 1, and increment for every change

File: commons/src/main/java/cern/molr/commons/commands/Start.java (hunk 31 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/commands/Start.java]: We said that there will be commands that are specific to some moles. A mole developer can create its own commands by implementing the MissionCommand interface. Implementing an interface instead of using a String field would allow to the developer to create more complex commands than simple instructions.

File: commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java [hunk 42]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * @author yassine-kr
+ */
+public class MissionExecutionNotAccepted extends Exception {
+
+    private static final long serialVersionUID = 195586081128114794L;
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java]: same about UID starting from 1

File: commons/src/main/java/cern/molr/commons/mission/Mole.java [hunk 43]
```diff
@@ -0,0 +1,33 @@
...
+package cern.molr.commons.mission;
+
+
+import cern.molr.commons.exception.IncompatibleMissionException;
+import cern.molr.commons.exception.MissionExecutionException;
+
+/**
+ * A {@link Mole} executes a given mission. Only a {@link Mole} knows how to run a mission.
+ *
+ * @param <I>
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/mission/Mole.java]: javadocs missing

File: commons/src/main/java/cern/molr/commons/mission/Mole.java [hunk 44]
```diff
@@ -0,0 +1,33 @@
...
+    /**
+     * Method which verify if a class type is compatible with the mole
+     *
+     * @param classType
+     *
+     * @throws IncompatibleMissionException
+     */
+    void verify(Class<?> classType) throws IncompatibleMissionException;
+
+    O run(Mission mission, I args) throws MissionExecutionException;
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/mission/Mole.java]: missing javadoc

File: commons/src/main/java/cern/molr/commons/request/MissionCommand.java [hunk 45]
```diff
@@ -0,0 +1,10 @@
+package cern.molr.commons.request;
+
+/**
+ * Generic command send by client to MolR server then forwarded to supervisor
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/MissionCommand.java]: sent

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java [hunk 46]
```diff
@@ -0,0 +1,35 @@
...
+    public MissionCommandRequest(String missionId, MissionCommand command) {
+        this.missionId = missionId;
+        this.command = command;
+    }
+
+    public String getMissionId() {
+        return missionId;
+    }
+
+    public void setMissionId(String missionId) {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: make this class immutable by removing the setters and making the class final

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java [hunk 47]
```diff
@@ -0,0 +1,35 @@
...
+/**
+ * A request sent to MolR server and a supervisor to execute a command
+ *
+ * @author yassine-kr
+ */
+public class MissionCommandRequest {
+    private String missionId;
+    private MissionCommand command;
+
+    public MissionCommandRequest() {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: remove

File: commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java [hunk 48]
```diff
@@ -2,15 +2,19 @@
...
  */
 
-package cern.molr.server.request;
+package cern.molr.commons.request.client;
 
-public class MissionCancelRequest {
+/**
+ * Request to get flux of events from the MolR server
+ */
+public class MissionEventsRequest {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java]: same about immutability and empty constructor

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java [hunk 49]
```diff
@@ -2,31 +2,42 @@
...
 
-public class MissionExecutionRequest<I> {
+/**
+ * This request is sent by the client to MolR server to instantiate a mission
+ *
+ * @param <I> the arguments type
+ *
+ * @author yassine-kr
+ */
+public class ServerInstantiationRequest<I> {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java [hunk 50]
```diff
@@ -2,31 +2,31 @@
...
 
-public class MissionExecutionRequest<I> {
+/**
+ * A request sent by the MolR server to supervisor to instantiate a mission
+ *
+ * @param <I> the arguments type
+ *
+ * @author yassine-kr
+ */
+public class SupervisorInstantiationRequest<I> {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java [hunk 51]
```diff
@@ -0,0 +1,30 @@
...
+ */
+
+package cern.molr.commons.request.server;
+
+/**
+ * A request sent by MolR server to the supervisor to get its state
+ *
+ * @author yassine-kr
+ */
+public class SupervisorStateRequest {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java [hunk 52]
```diff
@@ -1,20 +1,20 @@
...
-import java.util.ArrayList;
 import java.util.List;
 
 /**
  * A request sent by a supervisor to register itself in MolR Server
  *
- * @author yassine
+ * @author yassine-kr
  */
 public class SupervisorRegisterRequest {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java [hunk 53]
```diff
@@ -3,7 +3,7 @@
 /**
  * A request sent by a supervisor to unregister itself from MolR server
  *
- * @author yassine
+ * @author yassine-kr
  */
 public class SupervisorUnregisterRequest {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/response/Ack.java [hunk 54]
```diff
@@ -2,19 +2,20 @@
...
 /**
  * {@link Ack} is often used as an acknowledgement return type ( instead of void :) )
- * 
+ *
  * @author nachivpn
- * @author yassine
+ * @author yassine-kr
  */
-public class Ack{
+public class Ack {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/response/Ack.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponseBean.java [hunk 55]
```diff
@@ -4,19 +4,19 @@
 
 package cern.molr.commons.response;
 
-public class MissionExecutionResponseBean {
+/**
+ * A response bean to an instantiation request containing mission ID generated by MolR server
+ *
+ * @author yassine-kr
+ */
+public class InstantiationResponseBean {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/response/InstantiationResponseBean.java]: immutability
empty constructor

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 47 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: Delete this constructor

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java [hunk 56]
```diff
@@ -0,0 +1,35 @@
+package cern.molr.commons.request;
+
+/**
+ * A request sent to MolR server and a supervisor to execute a command
+ *
+ * @author yassine-kr
+ */
+public class MissionCommandRequest {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: missing hash and equals method

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 46 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: If we create it using the constructor we should delete these sets.

File: commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java [hunk 57]
```diff
@@ -2,15 +2,19 @@
...
 
     private String missionExecutionId;
 
-    public MissionCancelRequest(){}
-    
-    public MissionCancelRequest(String missionExecutionId){
+    public MissionEventsRequest() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java]: Delete this

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java [hunk 58]
```diff
@@ -2,31 +2,42 @@
...
 
     private String missionDefnClassName;
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: missionName

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java [hunk 59]
```diff
@@ -2,31 +2,42 @@
...
     private I args;
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: missionArguments to be more verbose

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java [hunk 60]
```diff
@@ -2,31 +2,42 @@
...
-    
-    public MissionExecutionRequest(){}
-    
-    public MissionExecutionRequest(String missionDefnClassName, I args){
+
+    public ServerInstantiationRequest() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: delete this

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java [hunk 61]
```diff
@@ -2,31 +2,42 @@
...
+    }
+
+    public ServerInstantiationRequest(String missionDefnClassName, I args) {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: missionName and missionArguments

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 49 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: missing hash and equals

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java [hunk 62]
```diff
@@ -2,31 +2,31 @@
...
 
     private String missionExecutionId;
-    private String moleClassName;
     private String missionContentClassName;
     private I args;
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: missionName and missionArguments

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java [hunk 63]
```diff
@@ -2,31 +2,31 @@
...
-    
-    public MissionExecutionRequest(){}
-    
-    public MissionExecutionRequest(String missionExecutionId, String moleClassName, String missionContentClassName, I args){
+
+    public SupervisorInstantiationRequest() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: delete this

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java [hunk 64]
```diff
@@ -2,31 +2,31 @@
...
+    }
+
+    public SupervisorInstantiationRequest(String missionExecutionId,
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: same here, names

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java (hunk 50 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: missing hash and equals

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 51 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: missing hash and equals

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java [hunk 65]
```diff
@@ -0,0 +1,30 @@
...
+
+    private String filter;
+
+    public SupervisorStateRequest() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: delete this

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java [hunk 66]
```diff
@@ -0,0 +1,30 @@
...
+package cern.molr.commons.request.server;
+
+/**
+ * A request sent by MolR server to the supervisor to get its state
+ *
+ * @author yassine-kr
+ */
+public class SupervisorStateRequest {
+
+    private String filter;
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: What is this filter used for?

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java (hunk 52 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: Just noticed that all of the fields on these DTOs should be final, for this and all the prevous ones.

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java [hunk 67]
```diff
@@ -1,20 +1,20 @@
...
 
     private String host;
     private int port;
     private List<String> acceptedMissions;
 
-    public SupervisorRegisterRequest(){}
+    public SupervisorRegisterRequest() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: delete this guy

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java (hunk 53 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java]: final field, remove empty constructor and add hash and equals

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java (hunk 52 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: also remove sets and add hash and equals

File: commons/src/main/java/cern/molr/commons/response/SupervisorState.java [hunk 68]
```diff
@@ -0,0 +1,37 @@
+package cern.molr.commons.response;
+
+import com.fasterxml.jackson.annotation.JsonIgnore;
+
+public class SupervisorState {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/response/SupervisorState.java]: immutable 
empty constructor

File: commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java [hunk 69]
```diff
@@ -0,0 +1,44 @@
...
+ *
+ * @author yassine-kr
+ */
+public interface SupervisorStateResponse extends TryResponse<SupervisorState> {
+
+    class SupervisorStateResponseSuccess extends TryResponseSuccess<SupervisorState>
+            implements SupervisorStateResponse {
+
+        public SupervisorStateResponseSuccess() {
+            super(null);
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java]: could we use optionals?

File: commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java [hunk 70]
```diff
@@ -1,69 +1,45 @@
...
-import cern.molr.commons.trye.TryResponseSuccess;
-import cern.molr.type.Ack;
-import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
+import cern.molr.commons.type.trye.TryResponse;
+import cern.molr.commons.type.trye.TryResponseFailure;
+import cern.molr.commons.type.trye.TryResponseSuccess;
 
 /**
- * Interface representing response to an unregister request
+ * Response to a unregister request sent back by the MolR server
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java]: an unregistered

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java (hunk 53 above)
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java]: I'm also seeing a lot of DTOs which only have one field inside.
I think these should be deleted and replaced in the code by the specific type.

On the supervisor why should I do:
```java
molrWebClient.post("/unregisterSupervisor", SupervisorUnregisterRequest.class, new SupervisorUnregisterRequest(10), SupervisorUnregisterResponse.class)
```

When I can simply create a ServerSupervisorClient or something, that extends the MolrWebClient and do:
```java
client.unregisterSupervisor(10)
```

and have it reuse the post inside of the MolrClient.
This makes the client API much simpler and hides some ugly details.

This comment is also valid in other places where the web client is used.

File: api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (timart1n) [reply api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java]: I think I would prefer to have a builder use the constructor with parameters.
@jcgarnier opinion?

File: commons/src/main/java/cern/molr/commons/type/trye/TryResponseFailure.java [hunk 71]
```diff
@@ -0,0 +1,41 @@
...
+ * Copyright (c) 2017 European Organisation for Nuclear Research (CERN), All Rights Reserved.
+ */
+
+package cern.molr.commons.type.trye;
+
+/**
+ * @author ?
+ * @author yassine-kr
+ */
+public class TryResponseFailure<T> extends Failure<T> implements TryResponse<T> {
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/type/trye/TryResponseFailure.java]: immutable and empty constructor

File: commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java [hunk 72]
```diff
@@ -0,0 +1,171 @@
...
+                } catch (JsonProcessingException e1) {
+                    return Mono.just(receivingExceptionHandler.getValue().apply(new
+                            Exception("unable to deserialize the input data")));
+                }
+            }
+        });
+    }
+
+    /**
+     * A function which can throws an exception
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java]: can throw

File: commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java [hunk 73]
```diff
@@ -1,54 +1,94 @@
...
-        /*
-        return Mono.create((emitter)->{
-            client.execute(URI.create("ws://"+host+":"+port+path),session -> {
-                WebSocketMessage::
-                session.r
-            });
-        });
-        */
+        /**
+         * Processor which which receives data from server
```
Comment (jcgarnier) [inline commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java]: which which

File: commons/src/main/java/cern/molr/commons/response/Ack.java (hunk 54 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/response/Ack.java]: Yes I pointed out that this should be done everywhere...

File: commons/src/main/java/cern/molr/commons/response/CommandResponse.java [hunk 74]
```diff
@@ -0,0 +1,64 @@
...
+            return message;
+        }
+
+        public void setMessage(String message) {
+            this.message = message;
+        }
+
+
+        @Override
+        public Map<String, String> getJsonMap() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/CommandResponse.java]: This is a no no for me. We have a json serializer/desserializer implementation for a reason. We should never do this ourselves.

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java [hunk 75]
```diff
@@ -0,0 +1,49 @@
...
+import cern.molr.commons.type.trye.TryResponse;
+import cern.molr.commons.type.trye.TryResponseFailure;
+import cern.molr.commons.type.trye.TryResponseSuccess;
+
+/**
+ * A response sent back to the client by the MolR server after receiving an instantiation request
+ *
+ * @author yassine-kr
+ */
+public interface InstantiationResponse extends TryResponse<InstantiationResponseBean> {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java]: I don't know but Im still not convined by this TryResponse thing. I believe this comes from nachis code? (he had something similar with the either).
Why not simply have a response class with a string or an int with the return code?

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java [hunk 76]
```diff
@@ -0,0 +1,49 @@
...
+
+    class InstantiationResponseSuccess extends TryResponseSuccess<InstantiationResponseBean>
+            implements InstantiationResponse {
+
+        public InstantiationResponseSuccess() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java]: Again remove this

File: commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java [hunk 77]
```diff
@@ -0,0 +1,39 @@
...
+import java.util.Map;
+
+/**
+ * Classes which has to be manually serializable. If the automatic serialization using Jackson library fails, the
+ * manual serialization is used.
+ * It is used only for failure response because there is no choice when the serialization of a failure fails
+ *
+ * @author yassine-kr
+ */
+public interface ManuallySerializable {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java]: I don't like this and in my opinion does not make sense.
What if the manual serialization fails? Are we gonna have a magic serialization which is used when the manual serialization fails, which is used when the normal serialization fails? See my point?
The serialization either passes or we have a problem and we should solve it.

File: commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java [hunk 78]
```diff
@@ -0,0 +1,39 @@
...
+
+    /**
+     * Serialization method which writes (as an array of two values) the object class name before writing the json map.
+     * This way of serialization is an option of Jackson library.
+     *
+     * @param object
+     *
+     * @return
+     */
+    static String serializeArray(ManuallySerializable object) {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java]: Seriously this looks really bad...

File: commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponse.java [hunk 79]
```diff
@@ -1,68 +1,45 @@
...
 /**
- * Interface representing response to a register request
+ * Response to a register request sent back by the MolR server
  *
- * @author yassine
+ * @author yassine-kr
  */
-@JsonDeserialize(using = SupervisorRegisterResponse.SupervisorRegisterResponseDeserializer.class)
-public interface SupervisorRegisterResponse extends TryResponse<SupervisorRegisterResponseBean>{
+public interface SupervisorRegisterResponse extends TryResponse<SupervisorRegisterResponseBean> {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponse.java]: Interface which only have 2 clases defined inside? Hummm something is wrong here.

File: commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponseBean.java [hunk 80]
```diff
@@ -1,22 +1,17 @@
 package cern.molr.commons.response;
 
 /**
- * Bean representing a response to a register request
+ * Bean response to a register request containing the supervisor ID generated by the MolR server
  *
- * @author yassine
+ * @author yassine-kr
  */
 public class SupervisorRegisterResponseBean {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponseBean.java]: Final field
remove empty constructor 
remove bean from name (everywhere)

File: commons/src/main/java/cern/molr/commons/response/SupervisorState.java (hunk 68 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/response/SupervisorState.java]: @jcgarnier 
What do you think of trying https://immutables.github.io/.
Since we have A LOT of these types of objects.

File: commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java (hunk 69 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java]: In my opinion I dont see why is this even here.
I would prefer to have a generic response with a code for ok and for failure.

File: commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java [hunk 81]
```diff
@@ -1,69 +1,45 @@
...
  *
- * @author yassine
+ * @author yassine-kr
  */
-@JsonDeserialize(using = SupervisorUnregisterResponse.SupervisorUnregisterResponseDeserializer.class)
-public interface SupervisorUnregisterResponse extends TryResponse<Ack>{
+public interface SupervisorUnregisterResponse extends TryResponse<Ack> {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java]: Again we have an interface which has 2 classes inside...

File: commons/src/main/java/cern/molr/commons/type/trye/Failure.java [hunk 82]
```diff
@@ -2,28 +2,26 @@
...
  * @param <T>
+ *
+ * @author nachivpn
+ * @author yassine-kr
  */
-public class Failure<T> extends Left<Throwable, T> implements Try<T>{
-   
+public class Failure<T> extends Left<Throwable, T> implements Try<T> {
+
     public Failure() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/type/trye/Failure.java]: Remove this

File: commons/src/main/java/cern/molr/commons/type/trye/Success.java [hunk 83]
```diff
@@ -2,31 +2,28 @@
...
- * 
- * @author nachivpn 
+ *
  * @param <T>
+ *
+ * @author nachivpn
+ * @author yassine-kr
  */
-public class Success<T> extends Right<Throwable, T> implements Try<T>{
+public class Success<T> extends Right<Throwable, T> implements Try<T> {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/type/trye/Success.java]: I think we should defenitly take a look into this sooner or later...
Just to return a successcful answer, which should simply be returning the correct value which would be serialized by the serializer we have to use a Success<T> that extends Right<Throwable, T> that implements Either<Throwable, T>.

Also of note that right Success<T> also implements Try<T> which extends Either<throwable, T>.

And this brings zero benefit as the conternder solution would simply to return T...
I seriously don't get this and HIGHLY advise in removing all of it...

File: commons/src/main/java/cern/molr/commons/type/trye/Success.java [hunk 84]
```diff
@@ -2,31 +2,28 @@
...
+
 
-    /**
-     * @param r
-     */
     public Success() {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/type/trye/Success.java]: Remove this

File: commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java [hunk 85]
```diff
@@ -0,0 +1,171 @@
...
+    }
+
+    /**
+     * Set the received Flux of messages
+     *
+     * @param preInput received flux of messages
+     *
+     * @return this builder to chain other methods
+     */
+    public DataExchangeBuilder<Input, Output> setPreInput(Flux<String> preInput) {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java]: This class is too complex... Please extract meaningful methods so we can understand what is actually going on here.

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java [hunk 86]
```diff
@@ -4,30 +4,60 @@
...
+                            .jackson2JsonDecoder(new Jackson2JsonDecoder(mapper, MediaType.APPLICATION_JSON));
+                }).build();
+        this.client = WebClient.builder().baseUrl("http://" + host + ":" + port).exchangeStrategies(strategies).build();
     }
 
-    public <I,O> CompletableFuture<O> post(String uri, Class<I> requestClass, I request, Class<O> responseClass) {
-        return CompletableFuture.supplyAsync(
+    public <I, O> CompletableFuture<O> post(String uri, Class<I> requestClass, I request, Class<O> responseClass) {
+
+        ExecutorService executorService = Executors.newSingleThreadExecutor();
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: Create a configurable executor in construction time.

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java [hunk 87]
```diff
@@ -4,30 +4,60 @@
...
+                            .jackson2JsonEncoder(new Jackson2JsonEncoder(mapper, MediaType.APPLICATION_JSON));
+                    clientDefaultCodecsConfigurer.defaultCodecs()
+                            .jackson2JsonDecoder(new Jackson2JsonDecoder(mapper, MediaType.APPLICATION_JSON));
+                }).build();
+        this.client = WebClient.builder().baseUrl("http://" + host + ":" + port).exchangeStrategies(strategies).build();
     }
 
-    public <I,O> CompletableFuture<O> post(String uri, Class<I> requestClass, I request, Class<O> responseClass) {
-        return CompletableFuture.supplyAsync(
+    public <I, O> CompletableFuture<O> post(String uri, Class<I> requestClass, I request, Class<O> responseClass) {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: I though we had agreed in using reactive only instead of mixing with futures at the end.

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java [hunk 88]
```diff
@@ -4,30 +4,60 @@
...
+
+        ExchangeStrategies strategies = ExchangeStrategies
+                .builder()
+                .codecs(clientDefaultCodecsConfigurer -> {
+                    clientDefaultCodecsConfigurer.defaultCodecs()
+                            .jackson2JsonEncoder(new Jackson2JsonEncoder(mapper, MediaType.APPLICATION_JSON));
+                    clientDefaultCodecsConfigurer.defaultCodecs()
+                            .jackson2JsonDecoder(new Jackson2JsonDecoder(mapper, MediaType.APPLICATION_JSON));
+                }).build();
+        this.client = WebClient.builder().baseUrl("http://" + host + ":" + port).exchangeStrategies(strategies).build();
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: http must be part of the host as we might decide to go for https in the future

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java [hunk 89]
```diff
@@ -4,30 +4,60 @@
...
                 () -> client.post().uri(uri)
-                .accept(MediaType.APPLICATION_JSON)
-                .body(BodyInserters.fromPublisher(Mono.just(request), requestClass)).exchange()
-                .flatMapMany(value -> value.bodyToMono(responseClass))
-                .doOnError(e -> {throw new CompletionException(e);})
-                .blockFirst());
+                        .accept(MediaType.APPLICATION_JSON)
+                        .body(BodyInserters.fromPublisher(Mono.just(request), requestClass)).exchange()
+                        .flatMapMany(value -> value.bodyToMono(responseClass))
+                        .doOnError(e -> {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: Small name

File: commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java [hunk 90]
```diff
@@ -1,54 +1,94 @@
...
+     * Method which sends a request to sever ans receive a flux of data from it
+     *
+     * @param responseType
      * @param <T>
-     * @return
+     *
+     * @return try elements, if the serialization of an element throws an exception, this exception is pushed to flux
      */
-    public <T> Mono<Flux<T>> receiveFlux(Class<T> type){
+    public <I, T> Flux<Try<T>> receiveFlux(String path, Class<T> responseType, I request) {
```
Comment (timart1n) [inline commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java]: reactive api

File: client/build.gradle (hunk 20 above)
Comment (yassine-kr) [reply client/build.gradle]: Actually this dependency is imported by spring-boot-starter-webflux: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j/usages
Not by slf4j as I said.

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 25 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: The constructor of MissionExecutionServiceImpl does not try to connect to the server. It sets only the host and port address of the MolR server. Using the default constructor tries to get these values from a properties file. A failing of retrieving these values should stop the application.

[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: Should we use a default configuration (default host and port)? Because I understood from your second comment that a default configuration should not be used.
Or it should only be used when the operator does not provide the properties file.

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 26 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: Because the constructor just sets the host and port of the MolR server. A connection exception could be thrown when waiting for the client controller contained in the stream returned by the instantiate method of the service.

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 27 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: This exception will be thrown in two cases:
- unable to read the properties file (file does not exist for example) IOException; in this case host and port values are undefined.
- the port value cannot be parsed to an integer, so the port is undefined.

The exception should also be thrown when the host or port properties are not defined in the properties file.

So the exception message can't contain the host and port.

File: .gitignore [hunk 91]
```diff
@@ -9,6 +9,9 @@
 *.war
 *.ear
 
+!gradle-wrapper.jar
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply .gitignore]: I thought that travis needs this file to build the project. I did the same as this repository:
https://github.com/streamingpool/streamingpool-core/tree/master/gradle/wrapper

File: api/src/main/java/cern/molr/commons/AnnotatedMissionMaterializer.java [hunk 92]
```diff
@@ -38,7 +35,8 @@ public Mission materialize(Class<?> classType) throws MissionMaterializationExce
         LOGGER.info("Materializing annotated mission class [{}]", classType.getCanonicalName());
         RunWithMole moleAnnotation = classType.getAnnotation(RunWithMole.class);
         if (null == moleAnnotation) {
-            throw new MissionMaterializationException(new IllegalArgumentException(String.format("Class type [%s] is not annotated with RunWithMole", classType)));
+            throw new MissionMaterializationException(new IllegalArgumentException(String.format("Class type [%s] is " +
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/commons/AnnotatedMissionMaterializer.java]: Where is the weird thing?

File: .gitignore (hunk 91 above)
[the remark this answers is not in the document]
Comment (timart1n) [reply .gitignore]: Travis needs it but if you remove this line it will be there

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 89 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: Do you mean the class name MolrWebClient or the parameter names requestClass and responseClass ?

File: commons/src/main/java/cern/molr/commons/type/trye/Failure.java (hunk 82 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/type/trye/Failure.java]: What should I remove exactly?

File: api/src/main/java/cern/molr/type/ManuallySerializable.java (hunk 16 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/type/ManuallySerializable.java]: done

File: api/src/main/java/cern/molr/type/either/Either.java (hunk 17 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/type/either/Either.java]: done

File: client-api/src/main/java/cern/molr/client/api/ClientMissionController.java (hunk 18 above)
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/ClientMissionController.java]: done

File: client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java (hunk 19 above)
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java]: done

File: client/src/main/java/cern/molr/client/SampleOperator.java (hunk 21 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/SampleOperator.java]: done

File: client/src/main/java/cern/molr/client/SampleOperator.java (hunk 22 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/SampleOperator.java]: done

File: client/src/main/java/cern/molr/client/SampleOperator.java (hunk 23 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/SampleOperator.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 28 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 30 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java (hunk 39 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java]: done

File: commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java (hunk 40 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java]: done

File: commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java (hunk 41 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/exception/CommandNotAcceptedException.java]: done

File: commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java (hunk 42 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/exception/MissionExecutionNotAccepted.java]: done

File: commons/src/main/java/cern/molr/commons/mission/Mole.java (hunk 43 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/Mole.java]: done

File: commons/src/main/java/cern/molr/commons/mission/Mole.java (hunk 44 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/Mole.java]: done

File: commons/src/main/java/cern/molr/commons/request/MissionCommand.java (hunk 45 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommand.java]: done

File: commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java (hunk 70 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java]: I think an unregistration  request

File: .gitignore (hunk 91 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply .gitignore]: It will be there if the .gitignore does not ignore it
```
# Package Files #
*.jar
*.war
*.ear
```
So I added an exception to accept gradle-wrapper.jar file

File: build.gradle [hunk 93]
```diff
@@ -2,71 +2,96 @@ allprojects {
     apply plugin: "idea"
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply build.gradle]: done

File: build.gradle [hunk 94]
```diff
@@ -2,71 +2,96 @@ allprojects {
...
 
-project(":supervisor") {
+project(":supervisor-api") {
     dependencies {
+        compile project(":commons")
+    }
+}
+
+project(":client") {
+    dependencies {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply build.gradle]: done

File: client-api/src/main/java/cern/molr/client/api/MissionDeploymentService.java [hunk 95]
```diff
@@ -2,17 +2,17 @@
...
+ * {@link MissionDeploymentService} is the client (developer) - server interface used to deploy (or submit) missions
+ *
  * @author nachivpn
+ * @author yassine-kr
  */
 public interface MissionDeploymentService {
 
-    public void deploy(Mission m);
-    
+    void deploy(String missionClassName);
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/MissionDeploymentService.java]: done

File: client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java [hunk 96]
```diff
@@ -0,0 +1,28 @@
...
+public interface MissionExecutionService {
+
+    /**
+     * A method which sends a mission instantiation request to the MolR server
+     *
+     * @param missionClassName the class name of the mission to be instantiated
+     * @param args             the mission arguments, can be null if the mission does not need any argument
+     * @param <I>              the argument type
+     *
+     * @return A future mission controller
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java]: done

File: client/src/main/java/cern/molr/client/SampleOperator.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/SampleOperator.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 97]
```diff
@@ -0,0 +1,117 @@
...
+            String host = properties.getProperty("host");
+            int port = Integer.parseInt(properties.getProperty("port"));
+
+            client = new MolrWebClient(host, port);
+            clientSocket = new MolrWebSocketClient(host, port);
+
+        } catch (Exception e) {
+            LOGGER.error("error while trying to get client properties", e);
+            client = new MolrWebClient("localhost", 8000);
+            clientSocket = new MolrWebSocketClient("localhost", 8000);
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: When should we use the default configuration?

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 98]
```diff
@@ -0,0 +1,117 @@
...
+
+            properties.load(input);
+
+            String host = properties.getProperty("host");
+            int port = Integer.parseInt(properties.getProperty("port"));
+
+            client = new MolrWebClient(host, port);
+            clientSocket = new MolrWebSocketClient(host, port);
+
+        } catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 99]
```diff
@@ -0,0 +1,117 @@
...
+        }
+    }
+
+    public MissionExecutionServiceImpl(String host, int port) {
+        client = new MolrWebClient(host, port);
+        clientSocket = new MolrWebSocketClient(host, port);
+    }
+
+    @Override
+    public <I> Mono<ClientMissionController> instantiate(String missionDefnClassName, I args) {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 100]
```diff
@@ -0,0 +1,117 @@
...
+
+        ExecutorService executorService = Executors.newSingleThreadExecutor();
+
+        ServerInstantiationRequest<I> execRequest = new ServerInstantiationRequest<>(missionDefnClassName, args);
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 101]
```diff
@@ -0,0 +1,117 @@
...
+                                }, InstantiationResponseBean::getMissionExecutionId))
+                        .thenApply(missionExecutionId -> new ClientMissionController() {
+                            @Override
+                            public Flux<MissionEvent> getFlux() {
+                                MissionEventsRequest eventsRequest = new MissionEventsRequest(missionExecutionId);
+                                return clientSocket.receiveFlux("/getFlux", MissionEvent.class, eventsRequest)
+                                        .doOnError((e) -> LOGGER.error("error while receiving events flux", e)).map(
+                                                (tryElement)
+                                                        -> tryElement
+                                                        .match(MissionException::new, Function.identity()));
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: A tryElement is an instance implementing the Either interface, the match method allows to apply a transformation to the instance (can for example return another instance of a new type). It has two parameters, the first one is the function to apply if the instance is a left value, and the second one is a function to apply if the instance is a right value. The two function must have the same return type.

File: commons/src/main/java/cern/molr/commons/events/MissionFinished.java [hunk 102]
```diff
@@ -0,0 +1,35 @@
...
+    private String missionClassName;
+    private Object result;
+    private String moleClassName;
+
+    public MissionFinished() {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionFinished.java]: Yes in the class MoleRunner when the mission is finished

File: commons/src/main/java/cern/molr/commons/events/MissionFinished.java [hunk 103]
```diff
@@ -0,0 +1,35 @@
...
+    }
+
+    public MissionFinished(String missionClassName, Object result, String moleClassName) {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionFinished.java]: done

File: commons/src/main/java/cern/molr/commons/mission/AnnotatedMissionMaterializer.java [hunk 104]
```diff
@@ -4,32 +4,38 @@
...
-import java.util.stream.Collectors;
 
 /**
  * Implementation of {@link MissionMaterializer} that can instantiate {@link Mission}s from {@link Class}es
  * annotated with {@link RunWithMole}
  *
  * @author tiagomr
+ * @author yassine-kr
  */
 public class AnnotatedMissionMaterializer implements MissionMaterializer {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/AnnotatedMissionMaterializer.java]: It was actually used by the deployment service (not yet implemented code). So I made it in commons module because I thought it could be needed by the client code or the server code too when implementing the infrastructure layer.

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 88 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 66 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: I thought that it could be useful in the future.

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 105]
```diff
@@ -0,0 +1,117 @@
...
+
+    @Override
+    public <I> Mono<ClientMissionController> instantiate(String missionDefnClassName, I args) {
+
+        ExecutorService executorService = Executors.newSingleThreadExecutor();
+
+        ServerInstantiationRequest<I> execRequest = new ServerInstantiationRequest<>(missionDefnClassName, args);
+        Mono<ClientMissionController> mono = Mono.<ClientMissionController>create((emitter) -> {
+            try {
+                emitter.success(client.post("/instantiate", ServerInstantiationRequest.class, execRequest,
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 66 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: Lets not add things that are not necessary.
Keep it simple. Later if we need it we add it.

File: api/src/main/java/cern/molr/commons/AnnotatedMissionMaterializer.java (hunk 92 above)
[the remark this answers is not in the document]
Comment (timart1n) [reply api/src/main/java/cern/molr/commons/AnnotatedMissionMaterializer.java]: When I was revieweing it had a weitrd formatting but it could be just my browser windows misbehaving. If its ok then there is nothing to do.

File: .gitignore (hunk 91 above)
[the remark this answers is not in the document]
Comment (timart1n) [reply .gitignore]: Ok leave it, we can change it later. I prefer to be more specific in my gitignores instead of using *.jar

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 89 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: I mean e. Use error or something similar.

File: commons/src/main/java/cern/molr/commons/type/trye/Failure.java (hunk 82 above)
Comment (timart1n) [reply commons/src/main/java/cern/molr/commons/type/trye/Failure.java]: Empty constructor.

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 66 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: done

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 89 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: done

File: api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java (hunk 1 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java]: Removed by using @ JsonProperty annotation

File: api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java (hunk 2 above)
Comment (yassine-kr) [reply api/src/main/java/cern/molr/mole/supervisor/MissionCommandRequest.java]: done

File: api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java]: Removed by using @ JsonProperty annotation

File: api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java [hunk 106]
```diff
@@ -1,12 +1,52 @@
...
+        @JsonIgnore
+        public boolean isAvailable() {
+            return numMissions<maxMissions;
+        }
+
+        public int getNumMissions() {
+            return numMissions;
+        }
+
+        public void setNumMissions(int numMissions) {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply api/src/main/java/cern/molr/server/StatefulMoleSupervisor.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 27 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: code updated

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java (hunk 29 above)
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done, displaying the command in a readable way depends on the MissionCommand implementation

File: commons/src/main/java/cern/molr/commons/commands/Start.java (hunk 31 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/commands/Start.java]: The way of representing the exchanged data between the framework components should be discussed. There are four kinds of exchanged data:
- The requests, they are simple final classes.
- The commands, are classes implementing the MissionCommand Interface.
- The responses, they are represented as interfaces extending the TryResponse interface, for each response there are a success implementation and failure implementation.
- The events, are classes implementing the MissionEvent interface.

File: commons/src/main/java/cern/molr/commons/events/MissionException.java (hunk 32 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionException.java]: done

File: commons/src/main/java/cern/molr/commons/events/MissionException.java (hunk 33 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionException.java]: setters removed.
The class should not be final to allow jackson to save the class name and construct the good instance when receiving an event. The data representation of exchanged data should be discussed. If we decide to use one class for events which can represents any kind of event, we can make the class final without any problem.

File: commons/src/main/java/cern/molr/commons/events/MissionFinished.java (hunk 34 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionFinished.java]: same as above

File: commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java (hunk 36 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java]: The data representation of exchanged data should be discussed.

File: commons/src/main/java/cern/molr/commons/events/MissionStarted.java (hunk 35 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionStarted.java]: empty constructor removed, for final same as above

File: commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java (hunk 37 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/SessionInstantiated.java]: done

File: commons/src/main/java/cern/molr/commons/events/SessionTerminated.java (hunk 38 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/SessionTerminated.java]: done

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 46 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 47 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java (hunk 48 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java]: class deleted

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 49 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java (hunk 50 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 51 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: filter field removed.
So the empty constructor could not be avoided.
I made the class final

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java (hunk 52 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java (hunk 53 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java]: done

File: commons/src/main/java/cern/molr/commons/response/Ack.java (hunk 54 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/Ack.java]: done

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponseBean.java (hunk 55 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/InstantiationResponseBean.java]: done

File: commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java (hunk 69 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/SupervisorStateResponse.java]: The responses representation should be discussed.

File: client-api/src/main/java/cern/molr/client/api/ClientMissionController.java [hunk 107]
```diff
@@ -0,0 +1,36 @@
...
+ * @author yassine-kr
+ */
+public interface ClientMissionController {
+
+    /**
+     * A method which gets an events flux generated by the supervisor where the mission is being executed
+     *
+     * @return
+     */
+    Flux<MissionEvent> getFlux();
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/ClientMissionController.java]: done

File: client-api/src/main/java/cern/molr/client/api/ClientMissionController.java [hunk 108]
```diff
@@ -0,0 +1,36 @@
...
+
+
+    /**
+     * A method which send a command to the supervisor where the mission is being executed
+     *
+     * @param command
+     *
+     * @return a future response which says whether the command was accepted or not
+     */
+    Mono<CommandResponse> instruct(MissionCommand command);
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/ClientMissionController.java]: done

File: client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java [hunk 109]
```diff
@@ -0,0 +1,28 @@
...
+     */
+    <I> Mono<ClientMissionController> instantiate(String missionClassName, I args);
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client-api/src/main/java/cern/molr/client/api/MissionExecutionService.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 110]
```diff
@@ -0,0 +1,117 @@
...
+
+    public MissionExecutionServiceImpl(String host, int port) {
+        client = new MolrWebClient(host, port);
+        clientSocket = new MolrWebSocketClient(host, port);
+    }
+
+    @Override
+    public <I> Mono<ClientMissionController> instantiate(String missionDefnClassName, I args) {
+
+        ExecutorService executorService = Executors.newSingleThreadExecutor();
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: the executor service is not used anymore in MissionServiceImpl

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 111]
```diff
@@ -0,0 +1,117 @@
...
+                        InstantiationResponse.class)
+                        .thenApply(tryResp -> tryResp.match(
+                                (Throwable e) -> {
+                                    throw new CompletionException(e);
+                                }, InstantiationResponseBean::getMissionExecutionId))
+                        .thenApply(missionExecutionId -> new ClientMissionController() {
+                            @Override
+                            public Flux<MissionEvent> getFlux() {
+                                MissionEventsRequest eventsRequest = new MissionEventsRequest(missionExecutionId);
+                                return clientSocket.receiveFlux("/getFlux", MissionEvent.class, eventsRequest)
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 112]
```diff
@@ -0,0 +1,117 @@
...
+                                                        -> tryElement
+                                                        .match(MissionException::new, Function.identity()));
+                            }
+
+                            @Override
+                            public Mono<CommandResponse> instruct(MissionCommand command) {
+                                MissionCommandRequest commandRequest = new MissionCommandRequest(missionExecutionId,
+                                        command);
+                                return clientSocket.
+                                        receiveMono("/instruct", CommandResponse.class, commandRequest)
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: done

File: client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java [hunk 113]
```diff
@@ -0,0 +1,117 @@
...
+                                        .map((tryElement) ->
+                                                tryElement.match(CommandResponse.CommandResponseFailure::new,
+                                                        Function.identity()));
+                            }
+                        }).get());
+            } catch (InterruptedException | ExecutionException e) {
+                emitter.error(e.getCause());
+            }
+        }).subscribeOn(Schedulers.fromExecutorService(executorService)).doOnTerminate(() -> executorService.shutdown());
+        return mono;
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply client/src/main/java/cern/molr/client/impl/MissionExecutionServiceImpl.java]: As I added methods to the socket client allowing it to create connection session for each kind of request (instantiate, getEventsStream, and instruct), the code of the MissionExecutionServiceImpl instantiate method became more simple.

File: commons/src/main/java/cern/molr/commons/events/MissionFinished.java (hunk 102 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionFinished.java]: empty constructor removed

File: commons/src/main/java/cern/molr/commons/events/MissionStarted.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/events/MissionStarted.java]: empty constructor removed

File: commons/src/main/java/cern/molr/commons/mission/MissionImpl.java [hunk 114]
```diff
@@ -43,30 +33,20 @@ public MissionImpl(String moleClassName, String missionContentClassName) {
...
 
-    public List<String> getTasksNames() {
-        return new ArrayList<>(tasks);
-    }
-
-    public void setMoleClassName(String moleClassName) {
-        this.moleClassName = moleClassName;
-    }
-
     public void setMissionDefnClassName(String missionContentClassName) {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/MissionImpl.java]: done

File: commons/src/main/java/cern/molr/commons/mission/MissionImpl.java [hunk 115]
```diff
@@ -78,7 +58,8 @@ public boolean equals(Object o) {
         MissionImpl service = (MissionImpl) o;
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/MissionImpl.java]: done

File: commons/src/main/java/cern/molr/commons/mission/MissionMaterializer.java [hunk 116]
```diff
@@ -2,17 +2,17 @@
...
-import cern.molr.exception.MissionMaterializationException;
+import cern.molr.commons.exception.MissionMaterializationException;
 
 /**
  * Used to converts a given mission definition class file into a mission object
- * 
+ *
  * @author nachivpn
  */
 public interface MissionMaterializer {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/MissionMaterializer.java]: done

File: commons/src/main/java/cern/molr/commons/mission/Mole.java [hunk 117]
```diff
@@ -0,0 +1,33 @@
...
+/**
+ * A {@link Mole} executes a given mission. Only a {@link Mole} knows how to run a mission.
+ *
+ * @param <I>
+ * @param <O>
+ *
+ * @author nachivpn
+ * @author yassine-kr
+ */
+public interface Mole<I, O> {
```
[the remark this answers is not in the document]
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/mission/Mole.java]: done

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 47 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 46 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java (hunk 57 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java]: done

Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/MissionEventsRequest.java]: class deleted

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 58 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 59 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 60 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 61 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java (hunk 62 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java (hunk 63 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java (hunk 64 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 65 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java (hunk 67 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java (hunk 53 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorUnregisterRequest.java]: done

File: commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java (hunk 72 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java]: done

File: commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java (hunk 73 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java]: done

File: commons/src/main/java/cern/molr/commons/response/CommandResponse.java (hunk 74 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/CommandResponse.java]: done

File: commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java (hunk 77 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java]: interface deleted

File: commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java (hunk 78 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/ManuallySerializable.java]: done

File: commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponse.java (hunk 79 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponse.java]: I used the same structure used by @nachivpn

File: commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java (hunk 90 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebSocketClient.java]: done

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 87 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: done

File: commons/src/main/java/cern/molr/commons/web/MolrWebClient.java (hunk 86 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/MolrWebClient.java]: executor service deleted

File: commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java (hunk 85 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/web/DataExchangeBuilder.java]: As I removed the manual serialization, the code is now more simple

File: commons/src/main/java/cern/molr/commons/type/trye/Success.java (hunk 84 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/type/trye/Success.java]: done

File: commons/src/main/java/cern/molr/commons/type/trye/Success.java (hunk 83 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/type/trye/Success.java]: Yes it is a bit complex without a real benefit.

File: commons/src/main/java/cern/molr/commons/type/trye/Failure.java (hunk 82 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/type/trye/Failure.java]: done

File: commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java (hunk 81 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/SupervisorUnregisterResponse.java]: @nachivpn code

File: commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponseBean.java (hunk 80 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/SupervisorRegisterResponseBean.java]: final field: done
empty constructor removed
there is an interface which is named SupervisorRegisterResponse.
The same for InstantiationResponseBean

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java (hunk 76 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java]: done

File: commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java (hunk 75 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/response/InstantiationResponse.java]: Should be discussed

File: commons/src/main/java/cern/molr/commons/type/trye/TryResponseFailure.java (hunk 71 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/type/trye/TryResponseFailure.java]: empty constructor removed.
The class can't be final because it is extended
setters removed by using some Jackson annotations

File: commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java (hunk 52 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/supervisor/SupervisorRegisterRequest.java]: done for requests classes and some other classes

File: commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java (hunk 56 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/MissionCommandRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java (hunk 49 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/client/ServerInstantiationRequest.java]: done

File: commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java (hunk 51 above)
Comment (yassine-kr) [reply commons/src/main/java/cern/molr/commons/request/server/SupervisorStateRequest.java]: done
